travis:
  secure:
    BINSTAR_TOKEN: l1hnikiUc+0DaCM57eL6H+yrqhPTBP0g6p6aNxugUwNwJ5/WexSY3n/iPb7U0DaIrXRAHrBp6sBb1mY94XEn0isXQ26Gwcxcll3t6kfvzxPAOSo4mGA4v+K+5gzkT14fxcujArOnRdnOfNZh7N8+GvxEBoi2wOo/IrqvlmzNDgLsXK2Ooeuu4XSVzbkGseFxV9QEWdHUVBCztq4eXc9o8JnPr411tlbN45DnsVAynicJTUabdKMpbzdtkun9juFAkPFiviiO1aL5YiAYoTU9lNyWmJ4/+jPJ0k0+r/UStI1N86rp+eWiYcLWxb6FIf0jU63IORrMquin9j+CId44LJhgcIG4ro8kyEL8XlvnH/NFo4vVJBm+R7cRum08h6vc9lS1AfiRzhvsM8Z/TUMRpekkoAC4NjbAjUCI7uD0kqBzVgshuiR9p2F8nKcnn3fOhKZjOWUr2MarV7PlLOvIQiZ6eYHaAo6xDigpUCvriNoHyMrADtcNP3unXwKYcNPuLD3UeeHIVdjvNtNXSfH4vwp0UvskZSX2faWf8TufcUw7sFjjsQ56ky/HU/ZcvFlqWIEe8zsfZgM3K51pcmKXCF+zXIENq9oY3qggqu1Vz/ODQ2fgCvyU9yjqebgMHJYKPO7s7q0VE/+HNdLEwF8PylfXTUWt/4JLq5KA0bW6V+M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
